# Generated by Django 3.2.13 on 2022-12-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/new')),
            ],
        ),
    ]
