# Generated by Django 3.2.13 on 2022-12-11 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='type',
            field=models.CharField(choices=[('ring', 'ring'), ('earrings', 'earrings'), ('sets', 'sets'), ('hairaccessories', 'hairaccessories')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
