# Generated by Django 3.2.13 on 2023-01-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
